#spring properties
spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s

#server properties
server:
  shutdown: graceful

# management
management:

  server.port: 9273
  endpoints:
    web:
      exposure.include: "*"
      base-path: "/"
      path-mapping.prometheus: "metrics"
  endpoint:
    prometheus.enabled: true
    metrics.enabled: false
    shutdown.enabled: false
    health.show-details: always
  trace.http.include: request-headers,response-headers,principal,remote-address,session-id
  health:
    diskspace.enabled: false
    rabbit.enabled: false
    mongo.enabled: false

  # micrometer
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true

# database
db:
  driver: org.postgresql.Driver
  dialect: org.hibernate.dialect.PostgreSQL82Dialect
  schema: public
  #todo:
  url: jdbc:postgresql://...
  catalog: ...

# custom settings
storage:
  type: memory
#  type: postgres
  algorithm: linked
#  algorithm: skiplist
#  algorithm: withfactor